### ISSUE TITLE
restrict access to rtf files?

### ISSUE THREAD

**Issue by arlogriffiths** [erc-dharma/tfc-campa-epigraphy#1]
Je viens de déplacer [un lot de fichiers rtf](https://github.com/erc-dharma/tfc-campa-epigraphy/tree/master/rtf) depuis le repo Campa-Epigraphy.

Est-il possible de limiter la visibilité/accessibilité de ce dossier aux seuls membres du projet?

**Comment by ajaniak** [comment]
Il est impossible de faire cela avec git. Tout le repository fonctionne avec les mêmes droits. 

Plusieurs solutions: 
- créer un nouveau repository privé pour le lot de fichiers
- stocker ce lot dans electronic-texts 
- changer la visibilité du repository de public à privé (mais cela va à l'encontre des engagements pris par DHARMA)

**Comment by arlogriffiths** [comment]
merci. on va garder les rtf en pleine visibilité.
