### ISSUE TITLE
spelling normalizations in translation and lexicon

### ISSUE THREAD

**Issue by arlogriffiths** [erc-dharma/tfc-campa-epigraphy#10]
il faut bien tenir compte des remarques dans mon articles (version 20240214):

p. 34
It is important to note that the marker transliterated as m̃ has nothing to do with /m/, but rather appears in the following four functions: [...] 4. to express a schwa vowel in the syllable nucleus (gam̃p = gəp).

p. 35
In periods and areas where the m̃ is not yet in use, or is used only sporadically, the functional scope of the marker ṁ (the Indic anusvāra) covers that of the m̃ described above.

La remarque p. 35 s'applique à tout ou partie du corpus Indrapura.

Du coup, dans ta traduction et dans tes apparts lexicographiques fondés sur C. 106, je propose les modifications suivantes :

Ricaṁm >> Ricəm
Avaṁk >> Avək

Enfin, coquille de ta part: Ñjun >> Ñjuṅ 

Tu revérifieras tes autres traductions ainsi que le vocabulaire que tu en as extrait dans cam-lexicon?

**Comment by salomepichon** [comment]
Je viens d'effectuer les modification nécessaires!
