### ISSUE TITLE
données sur ton travail dans teiHeader

### ISSUE THREAD

**Issue by arlogriffiths** [erc-dharma/tfc-campa-epigraphy#11]
@salomepichon —

je me mets à résoudre les erreurs de validation dans DHARMA_INSCIC00001.xml et trouve ces lignes dans le teiHeader:

```
	<respStmt>
					<resp>EpiDoc Encoding</resp>
					<persName ref="part:sapi">
						<forename>Salomé</forename>
						<surname>Pichon</surname>
					</persName>
				</respStmt>
				<respStmt>
					<resp>intellectual authorship of edition</resp>
					<persName ref="part:argr">
						<forename>Arlo</forename>
						<surname>Griffths</surname>
					</persName>
					<persName ref="part:sapi">
						<forename>Salomé</forename>
						<surname>Pichon</surname>
					</persName>
				</respStmt>
				<respStmt>
					<resp>Conversion of encoding for DHARMA</resp>
					<persName ref="part:sapi">
						<forename>Salomé</forename>
						<surname>Pichon</surname>
					</persName>
				</respStmt>
```

Personnellement, j'ai l'impression que tu n'as jamais touché à ce fichier (il n'y a pas de ligne `<change>` te concernant), que tu n'as pas d'autorité intellectuelle sur l'édition (car j'ai édité moi-même C. 1 avant que tu deviennes mon étudiante), et du coup qu'Axelle a dû insérer ces infos dans tous les fichiers qu'elle a convertis depuis l'ex-répositoire du Corpus des inscriptions du Campā. 

Le confirmes-tu?

Je devrai alors regarder au cas par cas si ces informations te concernant sont correctes ou non.

**Comment by salomepichon** [comment]
Effectivement je confirme ne pas avoir touché à ce fichier XML ni avoir travaillé sur cette inscription.

**Comment by arlogriffiths** [comment]
d'accord, merci, je vais donc regarder chaque teiHeader et modifier si besoin.
