### ISSUE TITLE
C. 148

### ISSUE THREAD

**Issue by arlogriffiths** [erc-dharma/tfc-campa-epigraphy#12]
- il semble qu'aucune valeur @n n'ait été déclaré sur sur le `<bibl>` pour Majumdar 1927
- peux-tu copier/coller l'édition https://dharmalekha.info/texts/DHARMA_INSCIC00148 dans le fichier txt sur electronic-texts? il faut juste t'assurer qu'il n'y a pas actuellement de remarques utiles dans ce fichier txt  qu'on perdrait
- la traduction reste à terminer

**Comment by arlogriffiths** [comment]
il faut quand même un mininum faire attention aux indication que les logiciels nous donnent quand il y a des défauts d'encodage:

<img width="885" alt="Capture d’écran 2024-04-07 à 16 22 47" src="https://github.com/erc-dharma/tfc-campa-epigraphy/assets/835603/35399054-9a4e-4217-ba66-8143fcab95fe">


malgré le fait que le logiciel n'indique pas d'erreur, tu n'a pas suivi EGD 9.1, o¡ù il est énoncé clairement que "after your `<div type="edition">` element, your document shall include a `<div type="apparatus">` containing the element  `<listApp>`; within `<listApp>`, each apparatus entry must be individually wrapped in the element `<app>`, ...". tu as oublié le `<listApp>`, ce qui avec l'absence de @n pour Majumdar explique pourquoi ton apparats s'affiche aussi densément: 

<img width="1193" alt="Capture d’écran 2024-04-07 à 16 26 46" src="https://github.com/erc-dharma/tfc-campa-epigraphy/assets/835603/99f6433a-0969-45e6-ac4b-c0c6796e6bd3">



<listApp>
<app loc="line">
<lem></lem>
<rdg source="bib:AuthorYear_01"></rdg>
</app>
</listApp>

**Comment by salomepichon** [comment]
- Lors d'une discussion que nous avions eu il y a quelques années sur l'encodage des `<bibl>`, j'avais noté qu'il fallait mettre un @n uniquement pour les références de la bibliographie primaire.

Jusqu'alors, Majumdar était en secondaire, comme dans le reste de mes encodages. Comme il apparaît dans l'apparatus, je viens donc de le déplacer en bibliographie primaire avec un @n="M". 

- Le `<listApp>` est également corrigé. 

- Concernant le copier/coller de l'édition https://dharmalekha.info/texts/DHARMA_INSCIC00148, le site est pour l'instant en maintenance, mais je le ferai dès qu'il sera accessible.

- Concernant la traduction, il manque effectivement la face A et les lignes B1-B8 en sanskrit.

**Comment by arlogriffiths** [comment]
merci. j'espère que tu pourras fournir sous peu une traduction intégrale en anglais, après quoi je m'attellerai à la peaufiner. pas besoin de garder cet issue ouvert, tu me diras quand il y a une traduction de proposée.
