### ISSUE TITLE
<p rend="stanza"> in translation

### ISSUE THREAD

**Issue by arlogriffiths** [erc-dharma/tfc-campa-epigraphy#15]
@michaelnmmeyer : do you understand why the schema rejects my use of `<p rend="stanza">` in the file DHARMA_INSCIC00137.xml? I am consulting @danbalogh about the other validation problem in project-documentation issue #301.

**Comment by michaelnmmeyer** [comment]
Have you pulled project-documentation recently? I am not seeing validation issues with this file.

**Comment by danbalogh** [comment]
I'm not getting an error in this file other than the message about `<l>` not being permitted in that context. Either the issue has been resolved in the meantime, or perhaps because the error message about `<l>` mentioned `<p rend="stanza">`, you thought that there was a problem with the latter.

**Comment by arlogriffiths** [comment]
I am up-to-date on project-documentation. (anyhow, validation is done online rather than locally, isn't it?) if I open the file DHARMA_INSCIC00137.xml in Oxygen, I get error messages for both cases of `<p rend="stanza">`, plus for the encoding as per #301 on project-documentation. However, if I open in VSC I only get the last error, and this seems to be what you have on your end. Maybe the fact that I haven't updated my version of Oxygen for several years is to blame. Anyhow, it seems to be a non-issue so I'll close this.
