### ISSUE TITLE
code erronée dans un html?

### ISSUE THREAD

**Issue by arlogriffiths** [erc-dharma/tfc-campa-epigraphy#7]
Cher Axelle,

L'autre jour en faisant un git pull j'ai reçu un html modifié, sans pour autant que le xml source semble avoir été modifié récemment:

<img width="603" alt="Capture d’écran 2021-08-03 à 06 08 23" src="https://user-images.githubusercontent.com/835603/127930069-924b80d8-45a8-4de5-8c27-14b3663a8039.png">

Quand je regarde le dernier commit généré par le workflow, je vois qu'une modification a affecté DHARMA_INSCIC00072.html  mais je ne sais pas comment le modification a été générée. Aussi, je vois qu'il y a des éléments bibliographiques qui viennent interrompre le paragraphe et que l'interruption semble être devenue plus grave après ce commit.

Pourrais-tu voir ce qui se passe?

Merci!

Arlo

**Comment by ajaniak** [comment]
Cher Arlo, 

Le problème provient de l'encodage qui est incomplet: `<bibl><ptr/><citedRange unit="item">1</citedRange><citedRange unit="page">3-7</citedRange></bibl>`. Le code cherche donc un short title déclaré comme un ensemble vide et comme certains tags en sont, il remonte les données associées qui peuvent évoluer selon les modifications faites sur zotero et qui explique que l'html soit mis à jour pour correspondre à la base de données.

**Comment by arlogriffiths** [comment]
Merci. J'ai nettoyé le fichier source.
